/* Icons, 1= default icon */
#define tk                                       1
#define Tk                                       1
/* Dialogs */
#define ID_COLORDLGTEMPLATE                      0x1001
#define ID_COLORDLG                              0x1002
#define ID_COLORWHEEL                            0x1003
#define ID_OK                                    0x1004
#define ID_CANCEL                                0x1005
#define ID_TKVERSION                             0x1006
/* Bitmaps */
#define buttons                                  0x2001
/* Cursors */
#define X_cursor                                 0x3001
#define arrow                                    0x3002
#define based_arrow_down                         0x3003
#define based_arrow_up                           0x3004
#define boat                                     0x3005
#define bogosity                                 0x3006
#define bottom_left_corner                       0x3007
#define bottom_right_corner                      0x3008
#define bottom_side                              0x3009
#define bottom_tee                               0x300A
#define box_spiral                               0x300B
#define center_ptr                               0x300C
#define circle                                   0x300D
#define clock                                    0x300E
#define coffee_mug                               0x300F
#define cross                                    0x3010
#define cross_reverse                            0x3011
#define crosshair                                0x3012
#define diamond_cross                            0x3013
#define dot                                      0x3014
#define dotbox                                   0x3015
#define double_arrow                             0x3016
#define draft_large                              0x3017
#define draft_small                              0x3018
#define draped_box                               0x3019
#define exchange                                 0x301A
#define fleur                                    0x301B
#define gobbler                                  0x301C
#define gumby                                    0x301D
#define hand1                                    0x301E
#define hand2                                    0x301F
#define heart                                    0x3020
#define xicon                                    0x3021
#define iron_cross                               0x3022
#define left_ptr                                 0x3023
#define left_side                                0x3024
#define left_tee                                 0x3025
#define leftbutton                               0x3026
#define ll_angle                                 0x3027
#define lr_angle                                 0x3028
#define man                                      0x3029
#define middlebutton                             0x302A
#define mouse                                    0x302B
#define pencil                                   0x302C
#define pirate                                   0x302D
#define plus                                     0x302E
#define question_arrow                           0x302F
#define right_ptr                                0x3030
#define right_side                               0x3031
#define right_tee                                0x3032
#define rightbutton                              0x3033
#define rtl_logo                                 0x3034
#define sailboat                                 0x3035
#define sb_down_arrow                            0x3036
#define sb_h_double_arrow                        0x3037
#define sb_left_arrow                            0x3038
#define sb_right_arrow                           0x3039
#define sb_up_arrow                              0x303A
#define sb_v_double_arrow                        0x303B
#define shuttle                                  0x303C
#define sizing                                   0x303D
#define spider                                   0x303E
#define spraycan                                 0x303F
#define star                                     0x3040
#define target                                   0x3041
#define tcross                                   0x3042
#define top_left_arrow                           0x3043
#define top_left_corner                          0x3044
#define top_right_corner                         0x3045
#define top_side                                 0x3046
#define top_tee                                  0x3047
#define trek                                     0x3048
#define ul_angle                                 0x3049
#define umbrella                                 0x304A
#define ur_angle                                 0x304B
#define watch                                    0x304C
#define xterm                                    0x304D
